linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (encoding/json.Encoder).Encode
      - (encoding/json.Decoder).Decode
      - (net/http.ResponseWriter).Write

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
