version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - (encoding/json.Encoder).Encode
      - (encoding/json.Decoder).Decode
      - (net/http.ResponseWriter).Write
